### ISSUE TITLE
[SLA Library] Make handshake function

### ISSUE THREAD

**Issue by Hyeongcheol-An** [KAIST-IS521/TeamThree#16]

**Comment by jhong3842** [comment]
openssl header 사용

설치
sudo apt-get install libssl-dev

**Comment by jhong3842** [comment]
참고 openssl manual

[메뉴얼]     man PEM
[참고 코드] http://webs.co.kr/?document_srl=365342

**Comment by jhong3842** [comment]
[참고] http://www.nico.schottelius.org/docs/a-small-introduction-for-using-gpgme/
[참고] http://www.linuxfromscratch.org/blfs/view/svn/postlfs/gpgme.html

**Comment by pr0v3rbs** [comment]
I referenced this document for compile gpgme c binary.

https://www.gnupg.org/documentation/manuals/gpgme/Building-the-Source.html#Building-the-Source
