### ISSUE TITLE
Team's public key

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/TeamThree#6]
In the [engineering.tex](https://github.com/KAIST-IS521/2017-Spring/blob/master/teams/engineering.tex),  there is a mention about team's public key.

> You can use one of the team member’s key, or you can simply create a new PGP key pair for the service.

Which way should we choose ?

**Comment by lbh0307** [comment]
I will vote on creating a new key pair for two reasons.
- It splits the usage for the keys.
- It prevents leakage of personal secret keys. Since we are preparing hacking challenge, I cannot sure we can trust PGP key that will be used in server even after CTF...

**Comment by seongil-wi** [comment]
I agree with you. Is there any other opinion?

**Comment by seongil-wi** [comment]
I agree with you. Is there any other opinion?

**Comment by pr0v3rbs** [comment]
I want to create a new key pair for this Activity, too.

Reason is same with @lbh0307.

**Comment by seongil-wi** [comment]
Okay. Than I will create a new PGP key pair for this activity.

Thank you!
